server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_task?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      servlet:
        multipart:
          max-request-size: 10MB
          max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapperxml/*.xml

httpUrl: http://127.0.0.1

logging:
  level.*: info,debug,error,warn
  level:
    com.admin.mapper: debug